### ISSUE TITLE
project wont run without build-essential...  

### ISSUE THREAD

**Issue by JohnMcLear** [byronsha/poker_playhouse#2]
node-sass module at fault?

```
gyp info using node-gyp@3.6.0
gyp info using node@13.10.1 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.17\n"
gyp verb get node dir no --target version specified, falling back to host node version: 13.10.1
gyp verb command install [ '13.10.1' ]
gyp verb install input version string "13.10.1"
gyp verb install installing version: 13.10.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 13.10.1
gyp verb build dir attempting to create "build" dir: /home/jose/poker_playhouse/node_modules/node-sass/build
gyp verb build dir "build" dir needed to be created? /home/jose/poker_playhouse/node_modules/node-sass/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /home/jose/poker_playhouse/node_modules/node-sass/build/config.gypi
gyp verb config.gypi checking for gypi file: /home/jose/poker_playhouse/node_modules/node-sass/config.gypi
gyp verb common.gypi checking for gypi file: /home/jose/poker_playhouse/node_modules/node-sass/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python2
gyp info spawn args [
gyp info spawn args   '/home/jose/poker_playhouse/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/jose/poker_playhouse/node_modules/node-sass/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/jose/poker_playhouse/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/jose/.node-gyp/13.10.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/jose/.node-gyp/13.10.1',
gyp info spawn args   '-Dnode_gyp_dir=/home/jose/poker_playhouse/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/jose/poker_playhouse/node_modules/node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /home/jose/.node-gyp/13.10.1
gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/home/jose/poker_playhouse/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/home/jose/poker_playhouse/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/home/jose/poker_playhouse/node_modules/which/which.js:80:29)
gyp ERR! stack     at /home/jose/poker_playhouse/node_modules/which/which.js:89:16
gyp ERR! stack     at /home/jose/poker_playhouse/node_modules/isexe/index.js:44:5
gyp ERR! stack     at /home/jose/poker_playhouse/node_modules/isexe/access.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:158:23)
gyp ERR! System Linux 4.15.0-91-generic
gyp ERR! command "/usr/bin/node" "/home/jose/poker_playhouse/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/jose/poker_playhouse/node_modules/node-sass
gyp ERR! node -v v13.10.1
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN poker_friends@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.1 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.5.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.5.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jose/.npm/_logs/2020-03-27T20_56_35_244Z-debug.log
```

**Comment by JohnMcLear** [comment]
Fixed using ``apt-get install build-essential`` but really that shouldn't be a dep should it? :D

**Comment by JohnMcLear** [comment]
```
/home/jose/.node-gyp/13.10.1/include/node/v8.h:3547:37: note:   candidate expects 3 arguments, 2 provided
/home/jose/.node-gyp/13.10.1/include/node/v8.h:3550:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                     ^~~
/home/jose/.node-gyp/13.10.1/include/node/v8.h:3550:37: note:   candidate expects 3 arguments, 2 provided
binding.target.mk:125: recipe for target 'Release/obj.target/binding/src/binding.o' failed
make: *** [Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory '/home/jose/poker_playhouse/node_modules/node-sass/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/jose/poker_playhouse/node_modules/node-gyp/lib/build.js:285:23)
gyp ERR! stack     at ChildProcess.emit (events.js:316:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.15.0-91-generic
gyp ERR! command "/usr/bin/node" "/home/jose/poker_playhouse/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/jose/poker_playhouse/node_modules/node-sass
gyp ERR! node -v v13.10.1
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN poker_friends@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.1 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.5.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.5.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jose/.npm/_logs/2020-03-27T21_06_08_429Z-debug.log
```
Still fails..
Mheh giving up.
